import React, { useState } from 'react'
import styled from 'styled-components';

const Container = styled.div`
.activeBroder {
  border-bottom: 2px solid #FF8057;
  padding-bottom: 11px;
  width: 100%;
  display: flex;         /* keeps full width and center content */
  align-items: center;
}

   @media (max-width: 991px) {
    .my-active-navbar {
    margin-top: 8px;  
    }
}
.progress-container {
  display: flex;
  align-items: center;
  width: 100%;
}

/* Background bar */
.progress-bar {
  width: 100%;
  height: 6px;
  background-color: #e5e5e5;     
  border-radius: 10px;
  overflow: hidden;
  position: relative;
}

.progress-fill {
  height: 100%;
  background-color: #4E5586;      
  border-radius: 10px;
  position: relative;
  transition: width 0.3s ease-in-out; 
}

.progress-circle {
  position: absolute;
  right: 0;
  top: 50%;
  transform: translate(50%, -50%);
  width: 12px;
  height: 12px;
  background-color: #4E5586;
  border-radius: 50%;
  border: 3px solid #fff;
  box-shadow: 0 0 4px rgba(0,0,0,0.3);
}

.progress-text {
  margin-left: 10px;
  font-weight: 600;
}
.my-form-check-input{
    background-color: #4E5586 !important;
    border-color: #4E5586 ;
}
`
const gemini = () => {

  const [active, setInActive] = useState('Default')

  return (
    <Container>
      <div>
        <div>
          <h4>Voices</h4>
          <p style={{ fontSize: '12px' }}>Configure how backup LLMs are used when the primary LLM fails.</p>
        </div>
        <div className='ps-4' style={{ backgroundColor: '#F1F1F9', paddingTop: '12px' }}>
          <div className="row">
            <div className={`col-4`}>
              <div className={active === 'Default' ? 'activeBroder' : ''} style={{ cursor: 'pointer' }} onClick={() => setInActive('Default')}>
                Default
              </div>
            </div>
            <div className={`col-4`}>
              <div className={active === 'Custom' ? 'activeBroder' : ''} style={{ cursor: 'pointer' }} onClick={() => setInActive('Custom')}>
                Custom
              </div>
            </div>
            <div className={`col-4`}>
              <div className={active === 'Disabled' ? 'activeBroder' : ''} style={{ cursor: 'pointer' }} onClick={() => setInActive('Disabled')}>
                Disabled
              </div>
            </div>
          </div>
        </div>
        <div className="row">
          {
            active === "Default" && (
              <>
                <div>
                  <div className='mt-3'>
                    <p className='mb-0' style={{ fontSize: "18px" }}>LLM</p>
                  </div>
                  <div className='p-2 mt-1' style={{ border: '1px solid #E4E7EB', borderRadius: '5px' }}>
                    <div className="row ps-2" >
                      <div className="col-5">
                        <div>
                          <p className='' style={{ margin: 'auto', fontSize: '14px' }}>Gemini 2.5 Flash</p>
                        </div>
                      </div>
                      <div className="col-4 pt-1" style={{ textAlign: 'center' }}>
                        <div >
                          <p className='mb-0' style={{ padding: '2px 4px', border: '#aaa', backgroundColor: '#DADBE1', fontSize: '10px', borderRadius: '10px', color: '#8B8B8B' }}>Primary</p>
                        </div>
                      </div>
                      <div className="col-lg-3 col-md-12 col-sm-12 " >
                        <div style={{ float: 'right' }}>
                          <svg width='10' height="14" viewBox="0 0 10 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.000101837 15.0237L0.964435 15.9996L9.04314 8.04911L1.06276 -8.22104e-05L0.0865394 0.958936L7.09786 8.03716L0.000101837 15.0237Z" fill="black" />
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <div>
                      <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Temperature</p>
                      <p style={{ fontSize: '12px', color: '#4E5586' }}>Control the creativity and randomness of the responses generated by the LLM.</p>
                    </div>
                    <div className="progress-container">
                      <div className="progress-bar">
                        <div
                          className="progress-fill"
                          style={{ width: `${75}%` }}
                        >
                          <div className="progress-circle"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="row mt-2">
                    <div className="col-lg-6 d-flex align-items-center">
                      <p className="mb-0">Thinking Budget</p>
                    </div>
                    <div className="col-lg-6 d-flex justify-content-end">
                      <div className="form-check form-switch">
                        <input
                          className="form-check-input my-form-check-input"
                          type="checkbox"
                          role="switch"
                          id="flexSwitchCheckChecked"
                        />
                      </div>
                    </div>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: '#4E5586' }}>Control how many internal reasoning tokens the model can use before responding.</p>
                  </div>
                  <div>
                    <div className="mb-3 mt-2" >
                      <input type="number" className="form-control form-focus label-color  heading-14" style={{ marginTop: '-4px' }} id="exampleFormControlInput1" placeholder="Enter Number" />
                    </div>
                  </div>
                  <div>
                    <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Limit token usage</p>
                    <p style={{ fontSize: '12px', color: '#4E5586' }}>The maximum number of tokens that the LLM can predict. A value of -1 means no limit.</p>
                  </div>
                  <div className="mb-3 mt-2" >
                    <input type="text" className="form-control form-focus label-color  heading-14" style={{ marginTop: '-4px' }} id="exampleFormControlInput1" placeholder="" />
                  </div>

                </div>
              </>
            )
          }

          {/* Custom Area  */}

          {
            active === "Custom" && (
              <>
                <div>
                  <div className='mt-3'>
                    <p className='mb-0' style={{ fontSize: "18px" }}>LLM</p>
                  </div>

                  <div className='p-2 mt-1' style={{ border: '1px solid #E4E7EB', borderRadius: '5px' }}>
                    <div className="row ps-2" >
                      <div className="col-5">
                        <div>
                          <p className='' style={{ margin: 'auto', fontSize: '14px' }}>Gemini 2.5 Flash</p>
                        </div>
                      </div>
                      <div className="col-4 pt-1" style={{ textAlign: 'center' }}>
                        <div >
                          <p className='mb-0' style={{ padding: '2px 4px', border: '#aaa', backgroundColor: '#DADBE1', fontSize: '10px', borderRadius: '10px', color: '#8B8B8B' }}>Primary</p>
                        </div>
                      </div>
                      <div className="col-lg-3 col-md-12 col-sm-12 " >
                        <div style={{ float: 'right' }}>
                          <svg width='10' height="14" viewBox="0 0 10 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.000101837 15.0237L0.964435 15.9996L9.04314 8.04911L1.06276 -8.22104e-05L0.0865394 0.958936L7.09786 8.03716L0.000101837 15.0237Z" fill="black" />
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className='mt-2'>
                    {/* <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Temperature</p> */}
                    <p style={{ fontSize: '14px', color: '#4E5586' }}>We recommend using at least two backup LLMs from different model providers to keep your conversations going in case of an outage.</p>
                  </div>
                  <div>
                    <div className='ps-2' style={{ border: '1px solid #E4E7EB', backgroundColor: '#f5f6f8', padding: '8px' }}>
                      <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#clip0_85_27)">
                          <path d="M9 16.3125C7.55373 16.3125 6.13993 15.8836 4.9374 15.0801C3.73486 14.2766 2.7976 13.1346 2.24413 11.7984C1.69067 10.4622 1.54586 8.99189 1.82801 7.57341C2.11017 6.15492 2.80661 4.85196 3.82928 3.82928C4.85196 2.80661 6.15492 2.11017 7.57341 1.82801C8.99189 1.54586 10.4622 1.69067 11.7984 2.24413C13.1346 2.7976 14.2766 3.73486 15.0801 4.9374C15.8836 6.13993 16.3125 7.55373 16.3125 9C16.3125 10.9394 15.5421 12.7994 14.1707 14.1707C12.7994 15.5421 10.9394 16.3125 9 16.3125ZM9 2.8125C7.77623 2.8125 6.57994 3.17539 5.56241 3.85528C4.54488 4.53518 3.75182 5.50153 3.2835 6.63215C2.81518 7.76277 2.69265 9.00687 2.93139 10.2071C3.17014 11.4074 3.75944 12.5099 4.62478 13.3752C5.49012 14.2406 6.59262 14.8299 7.79288 15.0686C8.99314 15.3074 10.2372 15.1848 11.3679 14.7165C12.4985 14.2482 13.4648 13.4551 14.1447 12.4376C14.8246 11.4201 15.1875 10.2238 15.1875 9C15.1875 7.35898 14.5356 5.78516 13.3752 4.62478C12.2148 3.4644 10.641 2.8125 9 2.8125Z" fill="#878787" />
                          <path d="M9 12.9375C8.85082 12.9375 8.70774 12.8782 8.60225 12.7727C8.49676 12.6673 8.4375 12.5242 8.4375 12.375V5.625C8.4375 5.47582 8.49676 5.33274 8.60225 5.22725C8.70774 5.12176 8.85082 5.0625 9 5.0625C9.14918 5.0625 9.29226 5.12176 9.39775 5.22725C9.50324 5.33274 9.5625 5.47582 9.5625 5.625V12.375C9.5625 12.5242 9.50324 12.6673 9.39775 12.7727C9.29226 12.8782 9.14918 12.9375 9 12.9375Z" fill="#878787" />
                          <path d="M12.375 9.5625H5.625C5.47582 9.5625 5.33274 9.50324 5.22725 9.39775C5.12176 9.29226 5.0625 9.14918 5.0625 9C5.0625 8.85082 5.12176 8.70774 5.22725 8.60225C5.33274 8.49676 5.47582 8.4375 5.625 8.4375H12.375C12.5242 8.4375 12.6673 8.49676 12.7727 8.60225C12.8782 8.70774 12.9375 8.85082 12.9375 9C12.9375 9.14918 12.8782 9.29226 12.7727 9.39775C12.6673 9.50324 12.5242 9.5625 12.375 9.5625Z" fill="#878787" />
                        </g>
                        <defs>
                          <clipPath id="clip0_85_27">
                            <rect width="18" height="18" fill="white" />
                          </clipPath>
                        </defs>
                      </svg>
                      &nbsp; <span>Add additional voice </span>
                    </div>
                  </div>
                  <div>
                    <div>
                      <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Temperature</p>
                      <p style={{ fontSize: '12px', color: '#4E5586' }}>Control the creativity and randomness of the responses generated by the LLM.</p>
                    </div>
                    <div className="row" style={{ color: '#797D8C', fontSize: '13px' }}>
                      <div className="col-lg-6 "><p className='mb-2'>More deterministic</p></div>
                      <div className="col-lg-6 text-end"><p className='mb-2'>More expressive</p></div>
                    </div>
                    <div className="progress-container">
                      <div className="progress-bar">
                        <div
                          className="progress-fill"
                          style={{ width: `${75}%` }}
                        >
                          <div className="progress-circle"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="row mt-2">
                    <div className="col-lg-6 d-flex align-items-center">
                      <p className="mb-0">Thinking Budget</p>
                    </div>
                    <div className="col-lg-6 d-flex justify-content-end">
                      <div className="form-check form-switch">
                        <input
                          className="form-check-input my-form-check-input"
                          type="checkbox"
                          role="switch"
                          id="flexSwitchCheckChecked"
                        />
                      </div>
                    </div>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: '#4E5586' }}>Control how many internal reasoning tokens the model can use before responding.</p>
                  </div>
                  <div>
                    <div className="mb-3 mt-2" >
                      <input type="number" className="form-control form-focus label-color  heading-14" style={{ marginTop: '-4px' }} id="exampleFormControlInput1" placeholder="Enter Number" />
                    </div>
                  </div>
                  <div>
                    <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Limit token usage</p>
                    <p style={{ fontSize: '12px', color: '#4E5586' }}>The maximum number of tokens that the LLM can predict. A value of -1 means no limit.</p>
                  </div>
                  <div className="mb-3 mt-2" >
                    <input type="text" className="form-control form-focus label-color  heading-14" style={{ marginTop: '-4px' }} id="exampleFormControlInput1" placeholder="" />
                  </div>

                </div>
              </>
            )
          }

          {/* Disabled Area  */}

          {
            active === "Disabled" && (
              <>
                <div>
                  <div className='mt-3' style={{ border: '1px solid #E4E7EB', backgroundColor: '#FFF6F6', padding: '8px', borderRadius: '5px' }}>
                    <div className="row">
                      <div className="col-lg-1">
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M6.83264 13.1667C3.33482 13.1667 0.499268 10.3312 0.499268 6.83337C0.499268 3.33555 3.33482 0.5 6.83264 0.5C10.3305 0.5 13.166 3.33555 13.166 6.83337C13.166 10.3312 10.3305 13.1667 6.83264 13.1667Z" stroke="#E6A157" />
                          <path d="M6.83203 9.99998V6.19995" stroke="#E6A157" stroke-linecap="round" />
                          <path d="M6.83105 4.43335C6.75762 4.43311 6.69824 4.37305 6.69824 4.29956C6.69849 4.22628 6.75777 4.16699 6.83105 4.16675C6.90454 4.16675 6.9646 4.22613 6.96484 4.29956C6.96484 4.3732 6.90469 4.43335 6.83105 4.43335Z" fill="#E3BD26" stroke="#E6A157" />
                        </svg>
                      </div>
                      <div className="col-lg-11">
                        <p style={{ color: '#EE8F69', fontSize: '13px' }}>Disabling backup LLMs means that if your primary LLM fails or becomes unavailable, the conversation will end abruptly. This is strongly discouraged for production use.</p>
                      </div>
                    </div>

                  </div>
                  <div className='mt-3'>
                    <p className='mb-0' style={{ fontSize: "18px" }}>LLM</p>
                  </div>
                  <div className='p-2 mt-1' style={{ border: '1px solid #E4E7EB', borderRadius: '5px' }}>
                    <div className="row ps-2" >
                      <div className="col-5">
                        <div>
                          <p className='' style={{ margin: 'auto', fontSize: '14px' }}>Gemini 2.5 Flash</p>
                        </div>
                      </div>
                      <div className="col-4 pt-1" style={{ textAlign: 'center' }}>
                        <div >
                          <p className='mb-0' style={{ padding: '2px 4px', border: '#aaa', backgroundColor: '#DADBE1', fontSize: '10px', borderRadius: '10px', color: '#8B8B8B' }}>Primary</p>
                        </div>
                      </div>
                      <div className="col-lg-3 col-md-12 col-sm-12 " >
                        <div style={{ float: 'right' }}>
                          <svg width='10' height="14" viewBox="0 0 10 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.000101837 15.0237L0.964435 15.9996L9.04314 8.04911L1.06276 -8.22104e-05L0.0865394 0.958936L7.09786 8.03716L0.000101837 15.0237Z" fill="black" />
                          </svg>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <div>
                      <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Temperature</p>
                      <p style={{ fontSize: '12px', color: '#4E5586' }}>Control the creativity and randomness of the responses generated by the LLM.</p>
                    </div>
                    <div className="row" style={{ color: '#797D8C', fontSize: '13px' }}>
                      <div className="col-lg-6 "><p className='mb-2'>More deterministic</p></div>
                      <div className="col-lg-6 text-end"><p className='mb-2'>More expressive</p></div>
                    </div>
                    <div className="progress-container">
                      <div className="progress-bar">
                        <div
                          className="progress-fill"
                          style={{ width: `${75}%` }}
                        >
                          <div className="progress-circle"></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="row mt-2">
                    <div className="col-lg-6 d-flex align-items-center">
                      <p className="mb-0">Thinking Budget</p>
                    </div>
                    <div className="col-lg-6 d-flex justify-content-end">
                      <div className="form-check form-switch">
                        <input
                          className="form-check-input my-form-check-input"
                          type="checkbox"
                          role="switch"
                          id="flexSwitchCheckChecked"
                        />
                      </div>
                    </div>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: '#4E5586' }}>Control how many internal reasoning tokens the model can use before responding.</p>
                  </div>
                  <div>
                    <div className="mb-3 mt-2" >
                      <input type="number" className="form-control form-focus label-color  heading-14" style={{ marginTop: '-4px' }} id="exampleFormControlInput1" placeholder="Enter Number" />
                    </div>
                  </div>
                  <div>
                    <p className='mb-0 mt-2' style={{ fontSize: '18px' }}>Limit token usage</p>
                    <p style={{ fontSize: '12px', color: '#4E5586' }}>The maximum number of tokens that the LLM can predict. A value of -1 means no limit.</p>
                  </div>
                  <div className="mb-3 mt-2" >
                    <input type="text" className="form-control form-focus label-color  heading-14" style={{ marginTop: '-4px' }} id="exampleFormControlInput1" placeholder="" />
                  </div>

                </div>
              </>
            )
          }
        </div>
      </div>
    </Container>
  )
}

export default gemini
